### ISSUE TITLE
No punliques las soluciones aun

### ISSUE THREAD

**Issue by camelCase1492** [RodrigoLlanes/AdventOfCode2022#1]
Bro no publiques las respuestas hasta que acabe el mes, que la gente se va a copiar

**Comment by RodrigoLlanes** [comment]
Mucha gente publica sus soluciones, por estos motivos:

- Son una buena forma de que la gente nueva que no sabe resolver los retos, las busque y aprenda. Incluso existe un [subreddit oficial](https://www.reddit.com/r/adventofcode/) que te recomiendo, donde se publican las respuestas en distintos lenguajes y se responden dudas (Aparte de memes y otras cosas).
- Los ganadores de la clasificación general resuelven en los primeros minutos, por lo que si te alguien espera a que salgan las soluciones para copiarlas, no podrá ganar nada.
- Y si te preocupa por la clasificación privada de ACM UPV, llevo 4 años participando y nunca han habido problemas de copia. Estamos hablando de levantarte pronto durante 25 días para copiar las soluciones de otros, no vale la pena el esfuerzo, el único motivo para participar es el orgullo, la diversión, el aprendizaje, o todas, jajaja.

Dicho todo esto, espero haber resuelto tu duda, si subes tus respuestas estaré encantado de comentarlas juntos y ver las distintas formas que tenemos de abordar el mismo problema, para aprender juntos y divertirnos, que al fin y al cabo es el objetivo de esta competición.
